"""add check execution fk

Revision ID: 84db4cb422c3
Revises: 
Create Date: 2025-12-31 23:42:39.036298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84db4cb422c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_executions_id'), table_name='check_executions')
    op.drop_table('check_executions')
    op.drop_index(op.f('ix_checks_id'), table_name='checks')
    op.drop_table('checks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('required_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('expected_status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latency_threshold_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interval_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('checks_pkey'))
    )
    op.create_index(op.f('ix_checks_id'), 'checks', ['id'], unique=False)
    op.create_table('check_executions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('check_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('missing_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('actual_status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('executed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('check_executions_pkey'))
    )
    op.create_index(op.f('ix_check_executions_id'), 'check_executions', ['id'], unique=False)
    # ### end Alembic commands ###
